dist: xenial
services: docker
language: bash
addons:
  apt:
    sources:
        - sourceline: 'deb http://archive.ubuntu.com/ubuntu bionic main universe'
    packages:
      - qemu-user-static
env:
    global:
        - QEMU_VER=v4.0.0
        - DOCKER_REPO=multiarch/alpine
        - LATEST_VERSION=v3.10
    matrix:
        - ARCH=s390x    VERSION=v3.7    QEMU_ARCH=s390x      TAG_ARCH=x86_64
        - ARCH=s390x    VERSION=v3.8    QEMU_ARCH=s390x    TAG_ARCH=x86_64
        - ARCH=s390x    VERSION=v3.9    QEMU_ARCH=x86_64    TAG_ARCH=x86_64
        - ARCH=s390x    VERSION=v3.10   QEMU_ARCH=i386      TAG_ARCH=x86
        - ARCH=s390x    VERSION=edge    QEMU_ARCH=i386      TAG_ARCH=x86
script:
    - sudo ./update.sh -a "$ARCH" -v "$VERSION" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO" -t "$TAG_ARCH" -l "$LATEST_VERSION"
    - docker images
